### PR TITLE
Doc: man: make config location configurable

### PR DESCRIPTION
**Pull request by vvidic**
Debian and Ubuntu use `/etc/default/sbd` for the config file.

### CODE REVIEW

**Comment by wenningerk** [comment]
test this please

**Comment by wenningerk** [comment]
This is definitely an improvement for debian-flavor distributions.
Does the man-page-section-name 'Config via sysconfig' still make sense in the debian-context? Or would there be something more comprehensive? Or is it just not worth the effort?

**Comment by wenningerk** [comment]
The low hanging fruit might be 'Config via /etc/sysconfig' vs. 'Config via /etc/default'.
But I'm fine with how it is atm if the term 'sysconfig' makes sense to a debian-guy ;-)

**Comment by vvidic** [comment]
I think `Config via sysconfig` should be fine. The main problem was that the config path listed in the man page was not functional on a Debian/Ubuntu system creating some confusion for the users.

**Comment by wenningerk** [comment]
> I think `Config via sysconfig` should be fine. The main problem was that the config path listed in the man page was not functional on a Debian/Ubuntu system creating some confusion for the users.

I'm aware of the base issue - actually I had stumbled over it already but doing the fix somehow slipped.
Just didn't want to leave it in a halve-baked state. But if you are telling me that 'sysconfig' doesn't lead to
confusion in the debian world I'm fine with it.

**Pull request merged**
