### PR TITLE
first travis test

### PR DESCRIPTION
**Pull request by wenningerk**
Not really a test but at least a verification of building and packaging for centos 6 / 7.
Feel free to add builds for other distros ( & real tests one day) ;-)

### CODE REVIEW

**Comment by krig** [comment]
It's a start!

There's the `tests/regression.sh` thing, I guess you could run that after calling `make`.

**Comment by wenningerk** [comment]
@krig: Let's see how well the device-mapper-stuff is working inside docker - haven't tried so far ...

**Comment by krig** [comment]
Yeah, I don't know much about that either unfortunately.

**Comment by wenningerk** [comment]
well ... strangely the symlinks under /dev/mapper are not created in docker but pulling that right it seems to work - just merged it

**Comment by krig** [comment]
Cool :)

**Pull request merged**
