### PR TITLE
Fix: add missing options to init script

### PR DESCRIPTION
**Pull request by vvidic**
Add status, restart and force-reload options.

### CODE REVIEW

**Comment by wenningerk** [comment]
I'm actually not packaging that script ...  but anyway looks as if you are pushing it towards LSB conventions.
If that is the case it should probably then really comply. I've done a little bit of work in that direction in PR#12 although I've never reworked it to be finally merged.

**Comment by kgaillot** [comment]
We should probably settle on a common approach between this and PR #12 . I think that one is more comprehensive but still has issues to resolve. I vaguely remember there being a good reason to use different scripts for use with pacemaker and pacemaker_remote but I can't think of any.

**Comment by wenningerk** [comment]
Guess it had to do with the possibility to enable/disable them independently.
Imagine some details - like the name of the remote-node - in the sbd-config
and then somebody starting pacemaker. If both pacemaker & pacemaker_remoted
would use the same sbd-service we would have a pacemaker-node that
uses the remote-node-name in the disk-slot. Otherwise sbd-service would be
disabled and thus not come up with pacemaker either making the node not
appear on the device (no sbd-fencing possible but at least no split-brain) or
pacemaker stop right away if watchdog-fencing is enabled.
Bringing something in that provides a proper system-v startup (incl. scriptlets)
as a by product would probably be desirable. At least instead of something
that looks a little bit like if it would be usable as an LSB-script - but not quite.
We might again open up the discussion if the services should be called *_helper
as in PR#12 (Intention behind that was iirc to shy people away from starting
these services manually. What speaks for it atm is that it matches what comes
with pacemaker. Making names of services & files configurable for the
packager might be a possibility as well).

**Comment by kgaillot** [comment]
I think it would be rare to switch a node back and forth from cluster node to remote node, and even more rare to enable sbd for only one of them. The main thing I think could be relevant is the LSB header, e.g. X-Start-Before. But that might be better handled in the pacemaker init scripts, e.g. Should-Start. If it's just stuff that is or should be in the environment file, I think it's reasonable to require the user to edit that file when switching back and forth between cluster and remote node.

If there is something that must be specific to pacemaker or pacemaker-remote, then instead of something like sbd_helper, I'd prefer something like sbd-for-pacemaker.

I agree that a fully proper init script would be more useful than tweaking sbd.sh.

**Comment by wenningerk** [comment]
Taken care of in PR#62

**Pull request closed without merging**
