### PR TITLE
Build: configure: remove extra configure.ac in tests

### PR DESCRIPTION
**Pull request by wenningerk**

### CODE REVIEW

**Comment by kgaillot** [comment]
Looks good to me. The only difference that wasn't brought over was CPPFLAGS/LIBS ... was that intentional?

**Comment by wenningerk** [comment]
> Looks good to me. The only difference that wasn't brought over was CPPFLAGS/LIBS ... was that intentional?

You mean brought over from the dropped configure.ac or pacemaker?
The CPPFLAGS/LIBS the dropped configure.ac had were a subset of what we have now - right? Guess additional flags & libs shouldn't hurt. The shared object might not be generically usable afterwards but we anyway don't need that here.

**Comment by kgaillot** [comment]
> > Looks good to me. The only difference that wasn't brought over was CPPFLAGS/LIBS ... was that intentional?
> 
> You mean brought over from the dropped configure.ac or pacemaker? The CPPFLAGS/LIBS the dropped configure.ac had were a subset of what we have now - right? Guess additional flags & libs shouldn't hurt. The shared object might not be generically usable afterwards but we anyway don't need that here.

The dropped configure.ac additionally had -Werror and $glib_CFLAGS/$glib_LIBS

**Comment by wenningerk** [comment]
> 
> The dropped configure.ac additionally had -Werror and $glib_CFLAGS/$glib_LIBS

What am I missing here?
Doesn't the top-level one start off with
```
CPPFLAGS="$CPPFLAGS -Werror $glib_CFLAGS $libxml_CFLAGS"
LIBS="$LIBS $glib_LIBS $libxml_LIBS"
```
and add some more dependent on tests?

**Comment by kgaillot** [comment]
> > The dropped configure.ac additionally had -Werror and $glib_CFLAGS/$glib_LIBS
> 
> What am I missing here? Doesn't the top-level one start off with
> 
> ```
> CPPFLAGS="$CPPFLAGS -Werror $glib_CFLAGS $libxml_CFLAGS"
> LIBS="$LIBS $glib_LIBS $libxml_LIBS"
> ```
> 
> and add some more dependent on tests?

Ah, my bad -- I was just looking at the diff, which didn't show that.

**Pull request merged**
