### PR TITLE
Add explanation about -v, -vv and -vvv mode

### PR DESCRIPTION
**Pull request by Splarv**

### CODE REVIEW

**Comment by wenningerk** [comment]
Can we make this a 1-liner like 'increase verbosity (verbose/debug/debug library)?

**Comment by Splarv** [comment]
> Can we make this a 1-liner like 'increase verbosity (verbose/debug/debug library)?

Why not, if this will be obvious not only for experienced pacemaker developers, but also for just newbie pacemaker user. I wrote this patch only because I knew about such functionality only after digging inside the source. I think you better know english and how better to say in english.

**Comment by wenningerk** [comment]
#96

**Comment by wenningerk** [comment]
guess merged PR#96 gives the information requested

**Pull request closed without merging**
