### PR TITLE
Fix: spelling errors

### PR DESCRIPTION
**Pull request by vvidic**
panicing -> panicking
allows to -> allows one to

### CODE REVIEW

**Comment by wenningerk** [comment]
Personally I would prefer something like:
"This allows setting a timeout, sbd would use on start-up, waiting for devices to appear."
But not being an English native-speaker I should probably leave that to others ;-)

**Comment by kgaillot** [comment]
Either is fine, but in manuals I prefer the imperative, e.g. "Use this to set ..." as it subtly encourages the user to action.

**Comment by wenningerk** [comment]
So something like: "Configure this timeout to make sbd wait for devices to appear on startup."

**Comment by wenningerk** [comment]
Taken care of in PR#62

**Pull request closed without merging**
