### PR TITLE
list/dump failures go to stderr, and log details for monitor failures in agent

### PR DESCRIPTION
**Pull request by gao-yan**

### CODE REVIEW

**Comment by kgaillot** [comment]
add to whitelist

**Comment by wenningerk** [comment]
Sounds quite reasonable.
Unfortunately fence_sbd (https://github.com/ClusterLabs/fence-agents/blob/master/agents/sbd/fence_sbd.py) is checking for the "not dumped" in stdout :-(
Atm I don't see a reason why fence_sbd shouldn't be able to search both stdout & stderr to simplify the dependency. But still we would be creating a dependency.

**Comment by gao-yan** [comment]
Good point. Do you mean by updating sbd.spec with "Conflicts: fence-agents < ..." when fence_sbd is ready?

**Comment by wenningerk** [comment]
Yes, the 'conflicts' should do the trick. Just wouldn't like to do that before there is actually a released version of fence_agents you can use to settle the conflict.

**Comment by wenningerk** [comment]
Can we leave the PR sitting as is till we can reference to
https://github.com/ClusterLabs/fence-agents/pull/297
with a release in sbd.spec?

**Comment by gao-yan** [comment]
Yes, makes sense.

**Comment by wenningerk** [comment]
Thanks to Oyvind we have a release to depend upon:
https://github.com/ClusterLabs/fence-agents/releases/tag/v4.5.0

**Comment by gao-yan** [comment]
Nice, thanks. I'm adding a "Conflicts" now into sbd.spec.in

**Comment by wenningerk** [comment]
Hmm ... just checked around a bit what is provided/required by the fence-agents-packages.
fence-agents-sbd requires fence-agents-common.
fence-agents is just provided by fence-agents-all.
As I see it it would thus be possible to just install fence-agents-common & fence-agents-sbd as a pure minimum for using rhcs-style-fencing on a shared sbd-disk.
Thus it sounds safer for me to conflict with older fence-agents-sbd (probably easier to follow as well later on ;-) ).

**Comment by gao-yan** [comment]
Good point.

**Pull request merged**
