### PR TITLE
Log: sbd-md: add a warning log if failed to open/read device on startup

### PR DESCRIPTION
**Pull request by gao-yan**
With failed sbd devices, previously without any hints from logs within
the whole startup wait time (120s by default), users would be confused
about why start of sbd service is being stuck.

### CODE REVIEW

**Comment by wenningerk** [comment]
As it is gonna be silent after the first failure (good thing to be silent then don't get me wrong ;-) ) wouldn't it make sense to as well tell how long this loop may last at max?

**Comment by gao-yan** [comment]
Makes sense. Actually practically it could also be limited by systemd's defaultTimeoutStartSec which usually defaults to 90s.  I've been thinking of probably explicitly setting TimeoutSec to > 120s in sbd.service. 

On the other hand, users always forget to set TimeoutSec when using SBD_DELAY_START with very long msgwait. So probably we could  set TimeoutSec to a generally long enough value such as 10min?

**Comment by wenningerk** [comment]
We could as well think of having a pre-exec-script that does some basic checking of the sbd-config against what is configured in systemd.
Of course sbd could pull that data directly from systemd as well but it would create systemd/dbus dependend code-parts  and pull in some libraries not used otherwise.
Haven't found an easy method to get the parameters into sbd via cmdline-param or environment otherwise. (something for the timeouts like "%n" for the unit-name, or a switch to tell systemd to convert most of the unit-parameters to environment-variables e.g.)

**Comment by zzhou1** [comment]
Great thanks Yan and Klause to add code to provide this informative message! It will save hours for some people, like me. FYI, I suffered very recently due to lack of this kind of information to diagnose ;)

**Comment by wenningerk** [comment]
We shouldn't forget about your comment about setting systemd timeouts properly. Some sanity-check of sbd-timouts against systemd-timeouts would definitely be a valuable addition.

**Comment by gao-yan** [comment]
I'm thinking of adding an ExecStartPre into sbd.service with work flow like:
```
# Sanity check with "systemctl show" and "systemctl show sbd.service" against /etc/sysconfig/sbd
# Return success if everything is fine, otherwise:

mkdir /run/systemd/system/sbd.service.d/

cat > /run/systemd/system/sbd.service.d/TimeoutStartSec.conf << EOF
[Service]
TimeoutStartSec=...
EOF

systemctl daemon-reload
```
What do you think?

**Comment by wenningerk** [comment]
Hmm ... actually not what I had thought of and I'm not systemd-expert enough to give an educated guess on if it is really advisable to do this kind of modification in pre-exec (haven't searched for already existent examples).
I would rather have thought of just a test like doing ```systemctl show sbd -p TimeoutStartUSec``` and checking that against what is configured in /etc/sysconfig/sbd. It should be possible to prevent unit-start from pre-exec.
If we want to go further needing the config read from the disk(s) as well we might not get around pulling the systemd-interface into sbd. Could think of using the pre-exec to put e.g. the timeout into the environment for later use by sbd on the other hand. Didn't check if it would even work but it would be hacky in any way.

**Comment by gao-yan** [comment]
I'm working on a pre-start configuration checker. Will get back soon.

**Pull request merged**
