### PR TITLE
Use /etc/default/sbd for configuration on Debian

### PR DESCRIPTION
**Pull request by vvidic**

### CODE REVIEW

**Comment by kgaillot** [comment]
Looks good to me, though you might want to take a look at pacemaker's approach: a --with-configdir option in configure.ac so you can use e.g. EnvironmentFile=-@CONFIGDIR@/sbd . That allows for other distros to specify their location too.

**Comment by vvidic** [comment]
Ok, I see what you mean. It will be a bigger change but I'll try to update the patch to use this.

**Comment by wenningerk** [comment]
pull-request #12 might be an interesting reference here as well ...

**Comment by vvidic** [comment]
Updated the patch to use the CONFIGDIR option, please review.

**Comment by kgaillot** [comment]
Looks great, thanks!

FYI newer autoconf versions define a variable for the run directory (/run vs /var/run), but unfortunately it will be a while before we can drop support for older versions.

**Pull request merged**
