### PR TITLE
Backward compatibility and another fix

### PR DESCRIPTION
**Pull request by gao-yan**

### CODE REVIEW

**Comment by wenningerk** [comment]
-c has never been in the man-page - bad enough - but since the default changes with this patch-set it probably should go to the man-page together with the change.

**Comment by gao-yan** [comment]
Probably. It was introduced only in 1.3.0, but has never been exposed either from man page or --help. I guess Andrew added it for his own purpose of experiment :-)

But I'm actually quite hesitating about how to expose such a new option that basically defaults to "enabled"...  SBD_PACEMAKER is used for switching both "-P" and "-c", which kind of provides a way to disable it already.

"-W" has been through the change of the default value:
https://github.com/ClusterLabs/sbd/commit/b96ac28a25f46442e7736c4894edac4b7baebf80
, and now it's "-P".  Specifying the options twice for disabling them seems not very ideal but probably is the best option for backward compatibility... Not sure if it's a good idea to change -c to be an option that requires an argument. But of course that way would not be consistent with "-W" and "-P". Hmm...

**Comment by wenningerk** [comment]
With pacemaker-checker now defaulting to 'on' cluster-checking implicitly changed the default as well.
Meaning what was really implemented and not what was stated in the config-file ;-)

I was not thinking of the case where one would like to disable it but for the case where it should be enabled without the pacemaker-checker. This might me useful to a certain extent on remote-nodes to have it check for liveness of pacemaker-remote-daemon.
Till now it was '-c' and now it would be '-P -P' instead.

Of course you are right that the help is missing '-c' as well ...
I would keep the implementation as suggested by your commit so that '-W', '-P' & '-c' are consistent.

I'm not sure if I understand you correctly here but the alternative to documenting '-c' would be to have it lurking around undocumented till eternity. And this can't really be the goal I guess.

**Comment by gao-yan** [comment]
I mean I'm not sure if it's really necessary to expose this option at least for now... We'd probably like to avoid introducing unnecessary complexity to users unless we really have use cases that require cluster check to be disabled/enabled separately from pacemaker check.

I'm probably missing anything, but AFAICT https://github.com/ClusterLabs/sbd/pull/14 requires pacemaker check, and cluster check doesn't have to be disabled for this case, right?

But of course if we had any reasonable use cases, we'd probably even need to introduce a SBD_CLUSTER option for it in sbd.sysconfig.

**Comment by wenningerk** [comment]
You are right #14 would require pacemaker-watcher. But unfortunately Andrew spotted a possible race - which is why it is not merged. So all we have so far is enabling cluster-watcher so that it at least checks for presence of pacemaker-remote-daemon.

**Pull request merged**
