### PR TITLE
Build: sbd-pacemaker: Query CIB directly with the API instead of get_cib_copy()

### PR DESCRIPTION
**Pull request by gao-yan**
get_cib_copy() has been dropped from pacemaker 2.0 branch as of:
https://github.com/ClusterLabs/pacemaker/commit/32c75b7be

### CODE REVIEW

**Comment by wenningerk** [comment]
query probably won't null current_cib in case of a failure.
At least in the case directly after free(current_cib) that would leave a reference to something already freed.

**Comment by gao-yan** [comment]
AFAICS, the function nulls the "*output_data" first:
```
cib_native_perform_op_delegate(): 353:
    if (output_data != NULL) {
        *output_data = NULL;
    }
```
Or am I missing anything?

**Comment by kgaillot** [comment]
I think this PR is a good idea regardless, but do you think we should add get_cib_copy() back to Pacemaker (still deprecated) to give people time to migrate to the new sbd? Or better to make a clean break, and require the newer sbd to work with the newer pacemaker?

**Comment by gao-yan** [comment]
If they would still need to adjust their old sbd code base to reference for example crm/compatibility.h so that it'd work with new pacemaker, that'd probably wouldn't help them much.

With this change of sbd, it'll work for both old or new pacemaker :)

**Comment by wenningerk** [comment]
@yan: Yes, you're probably fine assuming the cib_connected is set properly (as it should be done be connection_destroy) so it won't bail out before. But I don't know if it had been like that since ever ...

@ken: Probably good to enforce as much change as possible now ...

**Comment by gao-yan** [comment]
On 03/08/2018 04:54 PM, Gao,Yan wrote:
> AFAICS, the function nulls the "*output_data" first:
> 
> |cib_native_perform_op_delegate(): 353: if (output_data != NULL) { 
> *output_data = NULL; } |
> 
> Or am I missing anything?
But probably we better not assume anything... Better safe than sorry. 
I'm amending it.

**Comment by kgaillot** [comment]
@gao-yan 

> If they would still need to adjust their old sbd code base to reference for example crm/compatibility.h so that it'd work with new pacemaker, that'd probably wouldn't help them much.

I was thinking of restoring it where it was, rather than compatibility.h, and keeping the comment saying it's deprecated.

> With this change of sbd, it'll work for both old or new pacemaker :)

Yes but someone building pacemaker 2.0 will need to also build the newest sbd (if they use it). Maybe not too much to ask, just wondering ...

@wenningerk 

> Probably good to enforce as much change as possible now ...

Yes, but are we going to have an official sbd release with this before Pacemaker 2.0 is released? If not, we'll have a gap in sbd support (other than someone compiling or backporting from sbd master).

**Comment by wenningerk** [comment]
Guess sbd hasn't changed that much but pacemaker 2.0 compatibility. So I guess we wouldn't need much of a release-cycle there and just put a 1.3.2 or even 1.4.0 (pacemaker 2.0 compatibility?) label on it ;-)

**Comment by gao-yan** [comment]
On 03/08/2018 05:28 PM, Ken Gaillot wrote:
> @gao-yan <https://github.com/gao-yan>
> 
>     If they would still need to adjust their old sbd code base to
>     reference for example crm/compatibility.h so that it'd work with new
>     pacemaker, that'd probably wouldn't help them much.
> 
> I was thinking of restoring it where it was, rather than 
> compatibility.h, and keeping the comment saying it's deprecated.
Deprecating a deprecated thing again? :)  I have to admit maybe we 
should've changed sbd earlier, but the fact is sometimes we never notice 
things unless they are eventually dropped ;) I agree that pacemaker-2.0 
is the best opportunity to drop as much as we want though.

> 
>     With this change of sbd, it'll work for both old or new pacemaker :)
> 
> Yes but someone building pacemaker 2.0 will need to also build the 
> newest sbd (if they use it). Maybe not too much to ask, just wondering ...
Indeed. Given that the so versions of pacemaker libraries have been 
bumped, they will need to build/rebuild a sbd anyway. It probably won't 
be too much to as well just update sbd.

BTW, the commit has been amended. Amending doesn't seem to trigger 
notification.

**Pull request merged**
